// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace WoWDiscordBot.Service.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LastUpdateMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LastUpdateMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201803181833339_LastUpdateMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
